apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledmatrix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledmatrix-app
  template:
    metadata:
      labels:
        app: ledmatrix-app
    spec:
      containers:
        - name: ledmatrix-container
          image: nelsongeeko/led-matrix:0.9
          securityContext:
            privileged: true
          env:
            - name: IMAGE
              value: academy.jpg
          
